### ISSUE TITLE
can not build the project

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-metadata#5]
I have the following error that seems related to babel. An idea what I could no ?

```
 run `npm audit fix` to fix them, or `npm audit` for details
[lpatiny@power nmr-metadata]$ cheminfo build
./node_modules/median-quickselect/lib/median-quickselect.min.js
Module build failed: ReferenceError: Unknown plugin "remove-comments" specified in "/home/lpatiny/git/cheminfo/nmr-metadata/node_modules/median-quickselect/.babelrc" at 0, attempted to resolve relative to "/home/lpatiny/git/cheminfo/nmr-metadata/node_modules/median-quickselect"
    at /home/lpatiny/git/cheminfo/nmr-metadata/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/lpatiny/git/cheminfo/nmr-metadata/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
```

**Comment by targos** [comment]
I would rather remove the build script. You shouldn't have to build this project.

**Comment by lpatiny** [comment]
fixed
